"""vartotojai gali but darbuotojais

Revision ID: 6523590076e4
Revises: ad436dd1aaab
Create Date: 2022-02-23 21:25:39.220370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6523590076e4'
down_revision = 'ad436dd1aaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('registration', sa.String(length=6), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration'),
    sa.UniqueConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
