"""Initial migration.

Revision ID: 81e7801512b8
Revises: 6523590076e4
Create Date: 2022-02-23 21:27:00.905662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e7801512b8'
down_revision = '6523590076e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_worker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_worker')
    # ### end Alembic commands ###
